### ISSUE TITLE
[lib] path setting breaks watching

### ISSUE THREAD

**Issue by dmtrKovalenko** [rwasm/rsw-rs#8]
If `Cargo.toml` contains a lib path override watcher does not work at all. 

```toml
[lib]
crate-type = ["cdylib", "rlib"]
path = "./lib.rs"
```
